### PR TITLE
Update account login page

### PR DESCRIPTION
**Pull request by zhchlmm**
The style on the section element results in the login part is so narrow,  it's not as wide as origin abp theme, and remove the section style resolve it.

### CODE REVIEW

**Comment by zhchlmm** [comment]
## 修改前效果
修改前效果

## 修改后效果

**Comment by zhchlmm** [comment]
## 修改前
### **
## 修改后
修改后**

**Comment by zhchlmm** [comment]
## 修改前
修改前

## 修改后
修改后

**Comment by realLiangshiwei** [comment]
Thanks for your PR, but this is not what I want.

image

**Comment by realLiangshiwei** [comment]
I modified the width
https://github.com/liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/commit/a9a191a312def6db8ebae5594aa5349278a15c1a

**Pull request closed without merging**
